### ISSUE TITLE
golanci-lint wiki documentation

### ISSUE THREAD

**Issue by Integralist** [uber-go/nilaway#114]
👋🏻 

Just wanted to open this issue so I could keep track of when documentation is written for the wiki for golanci-lint configuration.

https://github.com/uber-go/nilaway/wiki/Configuration#golangci-lint

Thanks

**Comment by mfreeman451** [comment]
https://github.com/golangci/golangci-lint/issues/4211

**Comment by mfreeman451** [comment]
Looks like that integration isn't happening - https://github.com/golangci/golangci-lint/issues/4045

**Comment by Integralist** [comment]
Oh well, I'll close this off then 🙂

Thanks

**Comment by mfreeman451** [comment]
I'm surprised they didn't accept the PR for `NilAway` and just take it out of the default set.
