### ISSUE TITLE
Log.fatal is not considered terminal

### ISSUE THREAD

**Issue by nicois** [uber-go/nilaway#115]
When a nil test ends with a call to `log.Fatal`, the analyser does not realise that execution will end, and appears to consider it as the same as other log methods.

**Comment by ksurent** [comment]
Looks like a duplicate of #70.

**Comment by yuxincs** [comment]
We indeed have a lot of terminal functions (as well as other abnormal control flows) to handle. Closing this as a duplicate of #70 . Let's continue the discussion there!
