### ISSUE TITLE
An easy way to skip test code

### ISSUE THREAD

**Issue by karelbilek** [uber-go/nilaway#120]
There should be an easy way to skip all test code for analysis, as the nil checks are not that important there.

If there is a way then it should be documented.

(Reasoning: if there is a panic in test, it will fail the test, which is what I want in the first place.)

**Comment by dolmen** [comment]
`nilaway -test=false`

**Comment by karelbilek** [comment]
That is an idea or how it works now? It doesn't seem to work for me?
