### ISSUE TITLE
undefined: errors.Join

### ISSUE THREAD

**Issue by xiazemin** [uber-go/nilaway#128]
../../.gvm/pkgsets/go1.19/global/pkg/mod/go.uber.org/nilaway@v0.0.0-20231117175943-a267567c6fff/inference/inferred_map.go:147:17: undefined: errors.Join

**Comment by Jorropo** [comment]
@xiazemin you are running an unmaintained version of go, `errors.Join` was added in 1.20.

**Comment by dolmen** [comment]
@xiazemin [`go.mod`](https://github.com/uber-go/nilaway/blob/a267567c6ffff900df0c3394d031ee70079ec8df/go.mod#L3) says: minimum version is Go 1.20.

**Comment by yuxincs** [comment]
Thanks for the report!

As mentioned by others, we follow the same version support policy as the Go project: we support and test the last two major versions of Go. https://github.com/uber-go/nilaway#support

At this moment it means Go 1.20 and Go 1.21

Closing this, but feel free to re-open if this also occurs in Go 1.20 and 1.21 :)
