### ISSUE TITLE
Integrating with Bazel / Nogo

### ISSUE THREAD

**Issue by alex-mcleod** [uber-go/nilaway#131]
I am struggling to integrate nilaway with bazel. Can the documentation be updated to include an example of how to use nilaway with Bazel / Nogo?

**Comment by kpaulisse** [comment]
My quick and dirty hack with gazelle.

```go
// Package nilaway_import exists solely to have gazelle manage the dependencies
// for "nogo" to use Uber's "nilaway" analyzer
package nilaway_import

import _ "go.uber.org/nilaway"
```

```
nogo(
  # ...
  deps = TOOLS_NOGO + ["@org_uber_go_nilaway//:nilaway"] + ...
  #
)
```

I too would appreciate a less hacky implementation in the documentation.

**Comment by sonalmahajan15** [comment]
@alex-mcleod, the README is now updated with instructions for using NilAway with Bazel/nogo. I am closing this issue now. Feel free to re-open it if you face any problems.
