### ISSUE TITLE
False positive: Nilaway doesn't allow nil pointer in slice

### ISSUE THREAD

**Issue by karelbilek** [uber-go/nilaway#137]
I have this simple code.

```
package main

type FooType struct {
	Foo string
}

func AddSpace(foo *FooType) (*FooType, error) {
	if foo == nil {
		return nil, nil
	}
	return &FooType{
		Foo: foo.Foo + " ",
	}, nil
}

func AddSpaces(foos []*FooType) ([]*FooType, error) {
	res := make([]*FooType, len(foos))
	for i, foo := range foos {
		bar, err := AddSpace(foo)
		if err != nil {
			return nil, err
		}
		res[i] = bar
	}

	return res, nil
}

func main() {
	AddSpaces([]*FooType{{Foo: "foo"}, nil, {Foo: "foo"}})
}
```

This will never produce panic. However I get this from nilaway

```
.../main.go:23:12: error: Potential nil panic detected. Observed nil flow from source to dereference point: 
        -> something/main.go:9:10: literal `nil` returned from `AddSpace()` in position 0
        -> something/main.go:23:12: result 0 of `AddSpace()` assigned deeply into local variable `res`
```

You can argue that pointer in slice should never be nil, but that doesn't seem right to me. We have a logic where nils in slices are expected and handled correctly on other layers. (And if they are not, it should be reported _there_, not here.)

Here no nil is dereferenced. I don't do `res[i] = *bar` or anything.

**Comment by karelbilek** [comment]
(there is no error returned from the `AddSpace`, in real life, we have longer code that does more things and can return error)

**Comment by karelbilek** [comment]
Interestingly, this code, which does more or less the same thing, does _not_ produce this false positive.

```
func AddSpaces(foos []*FooType) ([]*FooType, error) {
	res := make([]*FooType, 0, len(foos))
	for _, foo := range foos {
		bar, err := AddSpace(foo)
		if err != nil {
			return nil, err
		}
		res = append(res, bar) // I can put nil here no problem
	}

	return res, nil
}
```

**Comment by sonalmahajan15** [comment]
You are right! NilAway currently supports `append` functionality correctly, but reports a false positive when doing deep assignment to a local variable. In fact, we already have a PR (#60 ) addressing this issue, which will be merged soon. I am keeping this issue open for now to track the progress of this feature.

Thanks for reporting! :)

**Comment by sonalmahajan15** [comment]
Closing this issue, since PR #60 addressing the problem discussed here has been merged.
