### ISSUE TITLE
Consider supporting `//nolint:nilaway` in standalone mode

### ISSUE THREAD

**Issue by philipaconrad** [uber-go/nilaway#143]
## Background

In PR #11, the original hard-coded `//nolint:nilaway` ignore directive support was removed. This change allowed Nilaway to more easily integrate with other linter/analysis drivers, but also *removed the ability for standalone Nilaway to ignore spurious errors*.

Waiting for other common linter drivers to integrate Nilaway may be futile-- see the consistently closed PRs and issues over in the `golangci-lint` repo, for instance. (The team there judged Nilaway to be too high a false positive rate for them to even *consider* integrating it as a supported linter. Using Nilaway as a plugin to `golangci-lint` is *technically* possible, but that style of integration is fairly unpleasant to implement and maintain, due to matching-version build requirements for both `golangci-lint` and the plugin.)

Note: Teams using the Bazel `nogo` integration may be able to use Nilaway a little-- I don't know anyone using Bazel for Golang development right now, so I can't comment on that integration.

## Proposal

If the standalone Nilaway driver under `cmd/nilaway` could have support for ignore directives again in some form, this would allow many teams and projects to try out the linter while it's maturing-- they will be able to work around the current high false-positive rate, and bring the linter into CI use cases more easily.

**Comment by philipaconrad** [comment]
I'll also note that I'm happy to take a stab at contributing back support for this feature if the team's okay with it. I'll take a look at what was removed in #11, and try to add back the essential bits, without b0rking the integration story outside of standalone mode.

**Comment by jaredmorrow** [comment]
+1, right now many people can only run nilaway in standalone mode and removing `//nolint:nilaway` support makes that impossible with the many false positives.
