### ISSUE TITLE
reading https://go.uber.org/nilaway/cmd/nilaway?go-get=1: 404 Not Found

### ISSUE THREAD

**Issue by sashamelentyev** [uber-go/nilaway#15]
When I install nilaway via `go install go.uber.org/nilaway/cmd/nilaway@latest` I get:
```console
go: go.uber.org/nilaway/cmd/nilaway@latest: unrecognized import path "go.uber.org/nilaway/cmd/nilaway": reading https://go.uber.org/nilaway/cmd/nilaway?go-get=1: 404 Not Found
        server response: 404 page not found
```

**Comment by maratrixx** [comment]
I had the same installation problem.

**Comment by 1saifj** [comment]
Same here

**Comment by yuxincs** [comment]
Thanks for your interests in NilAway, we're adding an alias for it under `go.uber.org`: https://github.com/uber/go.uber.org/pull/50, which should be merged soon. 

In the meantime if you'd like to try it out locally, feel free to clone the repo and build it by `go build ./cmd/nilaway`, the built binary will be available at the root of the repo. We'll keep you posted on the status :) 

Note: NilAway is still under heavy development. Expect false positives and breaking changes. Any feedback is greatly appreciated!

**Comment by sywhang** [comment]
This should be fixed now.
