### ISSUE TITLE
Can't pass `-test false` to `nilaway`

### ISSUE THREAD

**Issue by igoracmelo** [uber-go/nilaway#158]
I want to disable checking for test files, but when I try it I get an error:

```bash
$ nilaway -test false ./...
-: package false is not in std (/nix/store/y7abhs9glxfcg7lgcdc8i4ml5wg5ly92-go-1.21.4/share/go/src/false)
nilaway: error during loading
```

```bash
nilaway -V=full
/home/user/go/bin/nilaway version devel comments-go-here buildID=0ee4731574baa97d5a72091b355031b4dfd3de4a6ea862f20377ddf7c008219d
```

**Comment by gaby** [comment]
@igoracmelo Try `nilaway -test=false ./...`

**Comment by yuxincs** [comment]
The driver is using the `flag` package from the stdlib, where `-arg X` is only allowed for _non boolean_ arguments: https://pkg.go.dev/flag#hdr-Command_line_flag_syntax

Thanks @gaby ! Closing this issue 😃
