### ISSUE TITLE
Nilaway crashes on every computer I try it from

### ISSUE THREAD

**Issue by Starttoaster** [uber-go/nilaway#161]
Really excited about Nilaway, this is something a peer and I have been interested in and they recently informed me of this tool's existence. But having an issue where I install and run it against a Golang project, the way the readme describes. Just `go install [...]` and `nilaway ./...` from the repo's root. My 8-thread Intel i5-1135G7, 16GB of DDR4 memory, and 10GB of SWAP space get fully utilized by nilaway before linux OOM kills the nilaway processes. Is there some kind of nilaway log or something I can look for to give me a bit of insight as to what is going wrong here, or is that expected behavior? 

If it helps, the repo I'm running it against is here https://github.com/Chia-Network/chia-operator

My only thought, since nilaway returns no shell output during this, and this is a kubernetes operator project, is that scanning a project that pulls the kubernetes API as a dependency might be a tall order that requires perhaps a super computer.

**Comment by Starttoaster** [comment]
It looks like modifying the command to `nilaway -exclude-pkgs "k8s.io/api,k8s.io/apimachinery,k8s.io/client-go" ./... ` allows nilaway to actually run. My intent for using nilaway is pretty much to add it to a Makefile for all of my Golang projects, is there a good way to perhaps just tell nilaway that I only want it to search through my usage of pointers in local code (ie. code that exists within the repository)? Contributing upstream is something I do if I find an issue upstream, but my main priority is ensuring that the code _I write_ is sane and follows some potentially opinionated best practices. Currently, the thing that makes me less interested in doing-so is seemingly having to figure out in each project which packages I want to exclude to allow the tool to run, but would be nicer to just put in all of them something like `nilaway -local-only ./...`

**Comment by Starttoaster** [comment]
Interesting. Still spinning my wheels here, trying to test drive this tool a bit. I have some code in my repo that looks like this:
```
    if wallet.Spec.ChiaConfig.Resources != nil {
        deploy.Spec.Template.Spec.Containers[0].Resources = *wallet.Spec.ChiaConfig.Resources
    }
```
Which I changed to the following:
```
deploy.Spec.Template.Spec.Containers[0].Resources = *wallet.Spec.ChiaConfig.Resources
```

Nilaway found no issue with that. Maybe this tool doesn't do what I thought it did?

**Comment by Starttoaster** [comment]
I tried doing the reverse of the above with the `-include-pkgs` flag as well, not excluding anything explicitly, but only including modules I've written, and that has the same effect of ignoring the unchecked dereference on `*wallet.Spec.ChiaConfig.Resources`, where `wallet` is a type that I defined in my local code, but is being used as a value to set a field in an external dependency's struct. Just figured I'd give my tires another spin to see if this Issue is entirely pebkac, but it appears it is not.

**Comment by yuxincs** [comment]
Hi! Thanks for your interests in NilAway and we're excited to learn more about your experiences.

We probably should make analyzing only first party code default or at least add it to the README. But currently the NilAway tries to reason about _all_ code (including 3rd party dependencies). It is actually further explained in configurations: https://github.com/uber-go/nilaway/wiki/Configuration#general-flags (i.e., use `-include-pkgs` flag to _only_ analyze first party code, and try to apply optimistic defaults for 3rd party code).

For your particular example, that is something NilAway can do actually, and we call it struct initialization analysis in NilAway. That feature is still experimental-experimental (well, NilAway itself should be considered experimental, so...), and we've seen some performance penalty (as well as a higher rate of false positive) of it. We are evaluating more thoroughly and applying more optimizations to meet our performance promise. If you would like to try it out, you can add `//<nilaway struct enable>` at the beginning of your file to enable such support (we will make it a flag very soon to remove this hack).

Let us know what you think (and create issues if you find false positives and/or performance issues). 

I'm keeping this issue open for documentation fixes 😃

**Comment by sonalmahajan15** [comment]
@Starttoaster , for large projects, we suggest using a driver that supports modular analysis, such as Bazel/nogo. The [README](https://github.com/uber-go/nilaway/) is now updated with instructions for about this. I am closing this issue now. Feel free to re-open it, if you face any problems.
