### ISSUE TITLE
bool

### ISSUE THREAD

**Issue by ddkwork** [uber-go/nilaway#165]
```go
func (o *Stream) ToLines() (lines []string, ok bool) {
	//open C:\Users\Admin\Downloads\Compressed\xx\Driver-SoulExtraction.sln: The system cannot find the file specified.
	if strings.Contains(o.String(), "The system cannot find the file specified") {
		return
	}
	newReader := bufio.NewReader(o.Buffer)
	for {
		line, _, err := newReader.ReadLine()
		switch err {
		case io.EOF:
			return lines, true
		default:
			if !mylog.Error(err) {
				return
			}
		}
		lines = append(lines, string(line))
	}
}

If you call bool to check validity, the null pointer doesn't happen, and this pattern is used a lot in my repository to reduce the readability of nil keywords everywhere


https://github.com/ddkwork/golibrary/blob/master/stream/stream.go#L392

func SplitFileByLines(filePath string, size int) {
	lines, ok := ReadFileToLines(filePath)
	if !ok {
		return
	}


```

**Comment by ddkwork** [comment]
https://githubfast.com/ddkwork/golibrary/blob/master/stream/stream.go#L392

**Comment by ddkwork** [comment]
func FileExists(path string) bool {
	fi, err := os.Stat(path)
	if !mylog.Error(err) {
		return false
	}
	mode := fi.Mode()
	return !mode.IsDir() && mode.IsRegular()
}

**Comment by ddkwork** [comment]
response, err := o.Client.Do(request)
	if !mylog.Error(err) {
		return
	}
	defer func() {
		if response == nil {
			mylog.Error("response == nil")
			return
		}
		if o.debug {
			println(mylog.DumpResponse(response, true))
		}
		mylog.Error(response.Body.Close())
	}()
	switch response.StatusCode {
	case http.StatusOK, o.stopCode:

**Comment by sonalmahajan15** [comment]
@ddkwork , I believe PR #157 should solve the problem you have reported. For the next time, it would be great if you could distill the problem you are facing in a standalone simple test code, and put that in the issue along with some description of the problem. It will help us to understand the problem and quickly answer. I am closing this issue now, but feel free to reopen if the merged PR #157 did not solve your problem. Thanks!

**Comment by ddkwork** [comment]
> @ddkwork , I believe PR #157 should solve the problem you have reported. For the next time, it would be great if you could distill the problem you are facing in a standalone simple test code, and put that in the issue along with some description of the problem. It will help us to understand the problem and quickly answer. I am closing this issue now, but feel free to reopen if the merged PR #157 did not solve your problem. Thanks!

Thank you, girl. I will try.

**Comment by ddkwork** [comment]
> @ddkwork , I believe PR #157 should solve the problem you have reported. For the next time, it would be great if you could distill the problem you are facing in a standalone simple test code, and put that in the issue along with some description of the problem. It will help us to understand the problem and quickly answer. I am closing this issue now, but feel free to reopen if the merged PR #157 did not solve your problem. Thanks!

After a long period of testing, I found that when the pointer returns with error or the pointer returns with bool, after error or bool fails to return, the pointer should not check whether it is nil again, because I really can't find this kind of demo to reproduce it. On the contrary, the code that is modified after this due date is messy because there are too many checks. Or can you give a demo to reproduce these two cases and have to determine whether the pointer is nil or not?

**Comment by ddkwork** [comment]
https://github.com/ddkwork/golibrary/blob/master/stream%2Fnet%2FhttpClient%2FhttpClient.go#L101-L109

**Comment by ddkwork** [comment]
D:\workspace\workspace\branch\golibrary\stream\net\httpClient>nilaway  ./...
D:\workspace\workspace\branch\golibrary\stream\net\httpClient\httpClient.go:111:2: [31merror: [0mPotential nil panic detected. Observed nil flow from source to dereference point:
        - D:\workspace\workspace\branch\golibrary\stream\net\httpClient\httpClient.go:111:2: result 0 of [95m`NewRequest()`[0m lacking guarding; accessed field [95m`Header`[0m via the assignment(s):
                - [95m`http.NewRequest(...)`[0m to [95m`request`[0m at D:\workspace\workspace\branch\golibrary\stream\net\httpClient\httpClient.go:101:2

(Same nil source could also cause potential nil panic(s) at 1 other place(s): [36mD:\workspace\workspace\branch\golibrary\stream\net\httpClient\httpClient.go:109:2[0m.)

**Comment by ddkwork** [comment]
func RunEnglish() (ok bool) {
	client := http.Client{ //need point,this will be need check
		Transport:     nil,
		CheckRedirect: nil,
		Jar:           nil,
		Timeout:       0,
	}
	request, err := http.NewRequest(http.MethodGet, "https://www.google.com/", nil)
	if err == nil { // The detection here is the same as below, and the request null pointer check should be skipped
		return
	}
	request.Close = false
	response, err := client.Do(request) // should skip response, null pointer check
	//defer response.Body.Close() //return, and the following return will be executed here, so this code should be put behind to skip the case where the response is a null pointer
	if err == nil {
		return
	}
	defer response.Body.Close() //defer is just executing the code before return, err is nil then the response will never be nil, if err == nil then the previous code has been returned, it will not be executed here, and there will be no null pointer panic
	return true
}
