### ISSUE TITLE
Implement our own linter driver for NilAway as a standalone checker

### ISSUE THREAD

**Issue by yuxincs** [uber-go/nilaway#175]
There are 3 ways (although one of them is broken) to run NilAway:

(1) standalone checker: we use the standard linter driver from x/tools for running NilAway, such that NilAway can be run as a standalone executable.
(2) bazel/nogo: NilAway is configured as nogo analyzer and executed by nogo.
(3) golangci-lint: NilAway is configured as a linter in golangci-lint and executed by it.

(1) runs NilAway completely in memory, where NilAway has to re-analyze unmodified packages in consecutive runs, plus consuming a huge amount of memory sinc all facts are always stored instead of being fetched on demand (see #127, #161 for resource consumption when running NilAway). (2) and (3) offer fact caching, making them much better options for running NilAway given the sophistication of the analyses that NilAway does. 

However, (2) requires users to use bazel to build their Go projects, and [(3) is broken and likely won't work for some time ](https://github.com/uber-go/nilaway/tree/4335a432c225cf9de46a3baf2db3935bc115a376?tab=readme-ov-file#golangci-lint)(until NilAway is mature enough). Both of these "better" options seem to be out of reach for the majority of users. Therefore, most are simply using (1) and living with the performance penalties.

Given the demand, we might try to implement our own minimum caching linter driver that handles scheduling of NilAway sub-analyzers, as well as storing fact files to the filesystem (as well as loading them on-demand). We may need to re-invent some wheels, but in the long run could offer a lot of flexibilities for us (e.g., unlock us from being unable to fix driver-related issues, see https://github.com/uber-go/nilaway/labels/driver).

**Comment by yuxincs** [comment]
Meanwhile, since https://github.com/golang/go/issues/61324 proposal is accepted, let's wait some time for that to happen before moving this further. Hacking on top that importable linter driver seems a lot easier than to re-invent everything ourselves.

**Comment by getvictor** [comment]
@yuxincs It looks like https://github.com/golang/go/issues/61324 is closed. Can this move forward now?
