### ISSUE TITLE
GitHub Action for `nilaway` 

### ISSUE THREAD

**Issue by danielgospodinow** [uber-go/nilaway#182]
Hey, nilaway team! 👋🏼 

I love your tool and the idea behind it. Thus, since recently, I've started using it. 🚀 

I wanted to plug it into my GitHub Actions CI pipelines, but I couldn't find any Action that uses the tool.

That's why I've created one under this [qbaware/nilaway-action](https://github.com/qbaware/nilaway-action) repo and I've pushed it on GitHub's marketplace: [github.com/marketplace/actions/nilaway-action](https://github.com/marketplace/actions/nilaway-action).

Just giving a heads-up in case other users have the same use case as I did. 

Also, I'm open to collaborating on how to improve it further so that people find it even more useful.

**Comment by sonalmahajan15** [comment]
@danielgospodinow, this is fantastic! Thank you for the contribution! 👍

**Comment by yuxincs** [comment]
We always love community contributions! Thanks! I have added this as a community-maintained project in our wiki: https://github.com/uber-go/nilaway/wiki/Community-Maintained-Projects. 

(I'm also closing this as it is not really an issue 🤣)

**Comment by danielgospodinow** [comment]
Yay, thanks a lot to both of you! 🚀 (And yeah, I really didn't know how to communicate this 🤣, +1 on closing the issue 👍🏼)
