### ISSUE TITLE
Recent false positive from dd-trace-go SpanFromContext?

### ISSUE THREAD

**Issue by froodian** [uber-go/nilaway#199]
NilAway recently started complaining on some code it was happy with previously. The code looks like

```go
span, _ := tracer.SpanFromContext(ctx)
span.Finish(tracer.WithError(err))
```

and the error

```bash
/path/to/my-package/file.go:43:3: error: Potential nil panic detected. Observed nil flow from source to dereference point:
	- my-package/file.go:43:3: result 0 of `SpanFromContext()` lacking guarding; called `Finish()` via the assignment(s):
		- `tracer.SpanFromContext(ctx)` to `span` at my-package/file.go:42:3
```

but internally SpanFromContext, implemented [here](https://github.com/DataDog/dd-trace-go/blob/c95c5e723c897ab3f2c137e4563760e258c785c2/ddtrace/tracer/context.go#L24), cannot return nil:

```go
	if ctx == nil {
		return &traceinternal.NoopSpan{}, false
	}
	v := ctx.Value(internal.ActiveSpanKey)
	if s, ok := v.(ddtrace.Span); ok {
		return s, true
	}
	return &traceinternal.NoopSpan{}, false
```

**Comment by sonalmahajan15** [comment]
@froodian: This error is getting reported after the merging of PR #157 . The logic in that PR includes the assumption that if the function has an `ok-form`, then the caller can safely access other returns _only_ after checking `ok` to be true. Hence, NilAway fails fast if it finds that the `ok` return is suppressed. But clearly in this case the assumption is problematic, and we shouldn't fail fast. I'll investigate more and implement a solution to safeguard NilAway against such false positives. Thanks for reporting!

**Comment by sonalmahajan15** [comment]
Support added in PR https://github.com/uber-go/nilaway/pull/264 fixing this issue.
