### ISSUE TITLE
False positive with singletons

### ISSUE THREAD

**Issue by KristofferFJ** [uber-go/nilaway#208]
Hi there, I'm having an issue with false positive from a singleton in my project. I wrote sample code below.

```
package main

import (
	"fmt"
	"sync"
)

type Example struct {
	abc string
}

var once sync.Once
var instance *Example

func GetInstance() *Example {
	once.Do(func() {
		instance = &Example{
			abc: "Hello",
		}
	})
	return instance
}

func main() {
	fmt.Println(GetInstance().abc)
}

```

Running nilaway reports
<img width="659" alt="image" src="https://github.com/uber-go/nilaway/assets/12375426/d6f3c2d5-6fc4-45c4-b957-27c2a2c53b25">

**Comment by KristofferFJ** [comment]
Hi @sonalmahajan15,
Thanks a lot for the clarification and your suggestion of how we could fix it.
We will find a way to get around this for now, thank you.

**Comment by sonalmahajan15** [comment]
That sounds great. Thanks @KristofferFJ .
