### ISSUE TITLE
cpu max out on large project

### ISSUE THREAD

**Issue by ilovejs** [uber-go/nilaway#258]
Could you add more documentation about normal go project config ?
without bazel.
Or even better, run against k8s / docker

I ran against a large code base and it stuck, have to force shut down the PC

Possible Solution: make linter less eager, test on medium size project saying 10000 lines of go. See the cpu graph.
then, you can fine control it in late version.

**Comment by yuxincs** [comment]
Thanks for trying NilAway!

We added more doc in the README some time ago to make the following clear:

* By default NilAway analyzes all packages to gather most information, but it's recommended to use the `include-pkgs` flag to limit the analyses to a list of package prefixes for better performance.
* The standalone checker doesn't make use of the caching mechanism such that it's only good for evaluation purposes and not for production uses.

PRs welcome if the doc is still confusing :)
