### ISSUE TITLE
golangci-lint run issue

### ISSUE THREAD

**Issue by madneal** [uber-go/nilaway#261]
I have installed the nilway and golangci-lint according to the [instructions](https://github.com/uber-go/nilaway?tab=readme-ov-file#golangci-lint--v1570)

<img width="742" alt="image" src="https://github.com/uber-go/nilaway/assets/12164075/ba554975-56a6-42f4-af79-24ca23cc11aa">

<img width="1137" alt="image" src="https://github.com/uber-go/nilaway/assets/12164075/c8bdfae0-4bce-454f-bead-81f412d70589">

when try to `golangci-lint run`:

```
Error: build linters: plugin(nilaway): plugin "nilaway" not found
Failed executing command with error: build linters: plugin(nilaway): plugin "nilaway" not found
```

when try to run `golangci-lint custom`, no output generated.

But there should be some lints when using nilaway.

<img width="1003" alt="image" src="https://github.com/uber-go/nilaway/assets/12164075/84cdcacc-d4a5-4cd3-baf2-b7c6a963e8a8">

**Comment by yuxincs** [comment]
Per the instruction, `golangci-lint custom` builds the custom binary, and then you have to run the custom binary instead :)

PRs welcome if the current doc is confusing :)
