### ISSUE TITLE
Match intermediate variable names in want messages in tests

### ISSUE THREAD

**Issue by zzqatuber** [uber-go/nilaway#35]
Include the variable names in want messages in `testdata/src/go.uber.org/functioncontracts/inference/functioncontracts-with-inference.go`. See the discussion [here](https://github.com/uber-go/nilaway/pull/24/files/13f200aeebdad0f3d76c4628c43db89f7e0818a3#r1287483684).

**Comment by sonalmahajan15** [comment]
Closing this issue as it was addressed in PR #24.
