### ISSUE TITLE
Fix false positive for a corner case of short-circuiting expressions

### ISSUE THREAD

**Issue by yuxincs** [uber-go/nilaway#92]
NilAway is complaining about the latter dereference in the short-circuiting expressions:

```
func foo() bool {
  return s == nil || *s == ""
}
```

We have support for short-circuiting expressions in NilAway, but this is a corner case that we somehow missed. We should add support for it.

**Comment by daboross** [comment]
Same here, for

```
type AType struct {
	Field int
}

func F1(a *AType, b *AType) bool {
	return a != nil && b != nil && a.Field != b.Field
}

func TestF1(t *testing.T) {
	if F1(nil, nil) {
		t.Fatalf("f1 should not accept nil, nil")
	}
}```

**Comment by mavirn** [comment]
Similar experience here for this code block where short circuiting will prevent accessing a field of a nil item. 

```go
func (r *Room) getInfoAboutRoom() {
    hasField := r.Obj != nil && r.Obj.Field != nil
    ...
```

**Comment by davecgh** [comment]
It also is giving false positives for short circuiting slice indexing behind a length check which is very common and convenient operation because it returns 0 for both `nil` slices as well as non-nil empty slices meaning only a single check is necessary to cover both cases.

Here is a simple program to reproduce the false positive:

```Go
package main

import "fmt"

func isFirstByteZero(s []byte) bool {
        return len(s) > 0 && s[0] == 0
}

func main() {
        fmt.Println(isFirstByteZero(nil))
}
```

```
$ nilaway ./...
nilawayfp\main.go:6:23: error: Potential nil panic detected. Observed nil flow from source to dereference point:
        -> nilawayfp\main.go:10:30: literal `nil` passed as arg `s` to `isFirstByteZero()`
        -> nilawayfp\main.go:6:23: function parameter `s` sliced into
