### ISSUE TITLE
How to analyze Pkg.Imports

### ISSUE THREAD

**Issue by didebughu** [uber-go/nilaway#93]
First of all, thank you very much to the nilaway team
nilaway have the ability to recursively analyze the packages imported by the current package and and 3rd party packages.
I would like to ask how this is achieved, because my analyzer can only analyze the package passed in as a parameter.
thank you very much.

**Comment by yuxincs** [comment]
Hi @didebughu, great to see the interests you have in NilAway.

We are leveraging the Fact mechanism provided by the go/analysis package: https://pkg.go.dev/golang.org/x/tools/go/analysis#hdr-Modular_analysis_with_Facts

Basically we export data about what we have analyzed for a certain package, and when we are analyzing a downstream package we call `pass.AllPackageFacts()` to import the facts about upstream dependencies. Ensuring that the facts from upstream dependencies are available is the analyzer driver's responsibility :)

Hope this helps with the question, and feel free to reply/re-open for further discussion.

**Comment by didebughu** [comment]
thank you very much
