### ISSUE TITLE
False positive on empty ctx.Done() 

### ISSUE THREAD

**Issue by igorfraa** [uber-go/nilaway#97]
Per convention, `ctx.Done()` is normally nil for an empty context

example valid code:
```
func main() {
	ctx := context.Background()
	select {
	case <-ctx.Done():
		log.Println("context done")
	}
}
```
nilaway output:
```
 error: Potential nil panic detected. Observed nil flow from source to dereference point: 
        -> context/context.go:184:9: literal `nil` returned from `Done()` in position 0
        -> context/context.go:105:2: returned as result 0 from interface method `Context.Done()` (implemented by `emptyCtx.Done()`)
        -> example.go:11:9: result 0 of `Done()` uninitialized; nil channel accessed
```

**Comment by sonalmahajan15** [comment]
@igorfraa  - acknowledged. Thanks for reporting this issue. NilAway currently does not have support modeled for the `context` package. We will work on adding this support in NilAway. Also, feel free to raise a PR if you already have a working solution for this problem. :)

**Comment by FiloSottile** [comment]
This is not about `context` in particular. In general, receiving on a nil channel does not lead to a panic. It will block forever which might not be the desired outcome, but for example as part of a `select` it's potentially perfectly intended.

**Comment by orsinium** [comment]
Filippo is right, read from a nil channel doesn't panic by design and so should not be reported by NilAway. And the empty context is the best example of when it is an intended behavior.

**Comment by igorfraa** [comment]
looks like a specific case of a more general "nil channel inside select" https://github.com/uber-go/nilaway/issues/98

I will close this one in favour of !98 and will try to look into that
