### ISSUE TITLE
False positive for a nil channel select case

### ISSUE THREAD

**Issue by sonalmahajan15** [uber-go/nilaway#98]
Although a direct send/receive on a nil channel can cause a panic, the following code with use of `select` is safe. However, NilAway still reports an error.

```
func foo(aChan, bChan chan string) {
	aChan <- "abc"
	bChan <- "xyz"

	if true {
		aChan = nil
	}

	select {
	case a := <-aChan:   // error: "literal `nil` uninitialized; nil channel accessed"
		print(a)
	case b := <-bChan:
		print(b)
	}
}

func test() {
	aChan := make(chan string)
	bChan := make(chan string)

	go foo(aChan, bChan)
}
```

**Comment by bokwoon95** [comment]
> Although a direct send/receive on a nil channel can cause a panic

Actually, *both* writing and reading on a nil channel never panics 🙂. Not just on `select`. Here is some code to replicate:

```go
package main

import (
    "fmt"
    "time"
)

func main() {
    var aChan chan string = nil
    // Write to a nil channel; does not panic, blocks forever.
    go func() {
        aChan <- "sendValue"
    }()
    // Read from a nil channel; does not panic, blocks forever.
    go func() {
        receiveValue := <-aChan
        fmt.Println(receiveValue)
    }()
    // Print an empty string to console every 5 seconds to prevent deadlock.
    for {
        time.Sleep(5 * time.Second)
        fmt.Print("")
    }
}
```

**Comment by orsinium** [comment]
Here is a convenient table from "Concurrency in Go" of how each channel operation behaves on each channel type. As you can see, **only closing a nil channel may cause panic**.

![image](https://github.com/uber-go/nilaway/assets/9638362/92994192-fb72-415b-a02e-f1498ca0b1ef)

**Comment by roma-glushko** [comment]
Is there a way to ignore a specific line where the error happens? I have tried `nolint:nilaway` but that did not help 😞

**Comment by sonalmahajan15** [comment]
> Is there a way to ignore a specific line where the error happens? I have tried `nolint:nilaway` but that did not help 😞

@roma-glushko: If you are using the standalone `go/analysis` driver, then unfortunately `//nolint:nilaway` is not currently supported. In principle, we believe that enabling this support falls under the responsibility of the driver, as demonstrated by the support provided by `nogo`. Nevertheless, we have it on the roadmap to implement this support within NilAway itself to make it driver independent. (You can refer to https://github.com/uber-go/nilaway/issues/143#issuecomment-1843409098 for more context.)
